### ISSUE TITLE
prmd verify doesn't check references and allows schemas that fail with prmd doc

### ISSUE THREAD

**Issue by ernesto-jimenez** [interagent/prmd#107]
Here's an script to see the bug:

``` bash
#!/usr/bin/env bash

rm -rf schemata meta.json schema.json README.md
mkdir schemata

echo "---> Prepare"
# Create resource with broken $ref
prmd init resource | sed -e 's/schemata/schema/' > schemata/resource.json
echo '{
  "description": "Hello world prmd API",
  "id": "hello-prmd",
  "links": [{
  "href": "https://api.hello.com",
  "rel": "self"
  }],
  "title": "Hello Prmd"
}' > meta.json
echo "---> Combine"
prmd combine -m meta.json schemata > schema.json
echo "---> Verify"
prmd verify schema.json && echo "OK"
echo "---> Document"
prmd doc schema.json > README.md
```

And the output:

``` text
---> Prepare
---> Combine
---> Verify
OK
---> Document
Failed to dereference `/schema/resource/definitions/identity`
/Users/ernesto/.rvm/gems/ruby-2.1.1/gems/prmd-0.3.1/lib/prmd/schema.rb:44:in `block in dereference': undefined method `[]' for nil:NilClass (NoMethodError)
    from /Users/ernesto/.rvm/gems/ruby-2.1.1/gems/prmd-0.3.1/lib/prmd/schema.rb:43:in `each'
    from /Users/ernesto/.rvm/gems/ruby-2.1.1/gems/prmd-0.3.1/lib/prmd/schema.rb:43:in `dereference'
    from (erubis:96:in `block (2 levels) in result'
    from (erubis:93:in `gsub'
    from (erubis:93:in `block in result'
    from (erubis:91:in `each'
    from (erubis:91:in `result'
    from /Users/ernesto/.rvm/gems/ruby-2.1.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
    from /Users/ernesto/.rvm/gems/ruby-2.1.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
    from (erubis:6:in `block in result'
    from (erubis:4:in `each'
    from (erubis:4:in `map'
    from (erubis:4:in `result'
    from /Users/ernesto/.rvm/gems/ruby-2.1.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
    from /Users/ernesto/.rvm/gems/ruby-2.1.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
    from /Users/ernesto/.rvm/gems/ruby-2.1.1/gems/prmd-0.3.1/lib/prmd/commands/render.rb:9:in `render'
    from /Users/ernesto/.rvm/gems/ruby-2.1.1/gems/prmd-0.3.1/bin/prmd:87:in `<top (required)>'
    from /Users/ernesto/.rvm/gems/ruby-2.1.1/bin/prmd:23:in `load'
    from /Users/ernesto/.rvm/gems/ruby-2.1.1/bin/prmd:23:in `<main>'
    from /Users/ernesto/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/ernesto/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by aledalgrande** [comment]
Hi, this seems to be still a problem, was there any progress on it?
