### ISSUE TITLE
prmd combine error !!!

### ISSUE THREAD

**Issue by ruicloud** [interagent/prmd#153]
prmd 0.6.2 ,  
prmd combine -m meta.json schemata > schema.json
/home/nnn/.rvm/gems/ruby-2.1.2/gems/prmd-0.6.2/lib/prmd/commands/combine.rb:38:in `block in combine': undefined method`[]' for false:FalseClass (NoMethodError)
    from /home/nemo/.rvm/gems/ruby-2.1.2/gems/prmd-0.6.2/lib/prmd/commands/combine.rb:37:in `each'
    from /home/nemo/.rvm/gems/ruby-2.1.2/gems/prmd-0.6.2/lib/prmd/commands/combine.rb:37:in`combine'
    from /home/nemo/.rvm/gems/ruby-2.1.2/gems/prmd-0.6.2/bin/prmd:82:in `<top (required)>'
    from /home/nemo/.rvm/gems/ruby-2.1.2/bin/prmd:23:in`load'
    from /home/nemo/.rvm/gems/ruby-2.1.2/bin/prmd:23:in `<main>'

**Comment by rutaihwa** [comment]
I have get the same errors: Outpus is as follows
    /var/lib/gems/1.9.1/gems/prmd-0.8.0/lib/prmd/link.rb:45:in `<class:Link>': uninitialized constant Prmd::Link::OpenStruct (NameError)
	from /var/lib/gems/1.9.1/gems/prmd-0.8.0/lib/prmd/link.rb:2:in `<module:Prmd>'
	from /var/lib/gems/1.9.1/gems/prmd-0.8.0/lib/prmd/link.rb:1:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/prmd-0.8.0/lib/prmd.rb:5:in `require_relative'
	from /var/lib/gems/1.9.1/gems/prmd-0.8.0/lib/prmd.rb:5:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/prmd-0.8.0/bin/prmd:3:in `require_relative'
	from /var/lib/gems/1.9.1/gems/prmd-0.8.0/bin/prmd:3:in `<top (required)>'
	from /usr/local/bin/prmd:23:in `load'
	from /usr/local/bin/prmd:23:in `<main>'

**Comment by geemus** [comment]
@rutaihwa older versions of ruby don't automatically include openstruct. If you use a newer version it should fix this. Alternatively, the code on master has an explicit require, though I haven't had an opportunity to release it just yet.

**Comment by rutaihwa** [comment]
@geemus Thanks, that was the error :+1:
