### ISSUE TITLE
Issue generating documentation

### ISSUE THREAD

**Issue by anthonator** [interagent/prmd#197]
I'm having issues generating documentation with the following schema:

```json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "id": "schemata/oauth2",
  "title": "Captivated Customer - OAuth2",
  "description": "Managing app accesss using OAuth2",
  "type": ["object"],
  "definitions": {
    "access_token": {
      "description": "Credentials used to access protected resources",
      "example": "asdf",
      "type": ["string"]
    }
  },
  "links": [
    {
      "title": "Request a User Access Token",
      "description": "Obtain a new access token for a specific user",
      "href": "/oauth/token",
      "method": "POST",
      "rel": "create"
    }
  ]
}
```

which combines into:

```json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema",
  "definitions": {
    "oauth2": {
      "$schema": "http://json-schema.org/draft-04/hyper-schema#",
      "title": "Captivated Customer - OAuth2",
      "description": "Managing app accesss using OAuth2",
      "type": [
        "object"
      ],
      "definitions": {
        "access_token": {
          "description": "Credentials used to access protected resources",
          "example": "asdf",
          "type": [
            "string"
          ]
        }
      },
      "links": [
        {
          "title": "Request a User Access Token",
          "description": "Obtain a new access token for a specific user",
          "href": "/oauth/token",
          "method": "POST",
          "rel": "create"
        }
      ]
    }
  },
  "properties": {
    "oauth2": {
      "$ref": "#/definitions/oauth2"
    }
  },
  "type": [
    "object"
  ]
}
```

When running ```doc``` I get the following:

```
/Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/json-1.8.2/lib/json/common.rb:285:in `generate': only generation of JSON objects or arrays allowed (JSON::GeneratorError)
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/json-1.8.2/lib/json/common.rb:285:in `pretty_generate'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/prmd-0.7.0/lib/prmd/templates/schemata/link.md.erb:71:in `result'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/prmd-0.7.0/lib/prmd/template.rb:64:in `render'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/prmd-0.7.0/lib/prmd/templates/schemata.md.erb:28:in `block in result'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/prmd-0.7.0/lib/prmd/templates/schemata.md.erb:26:in `each'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/prmd-0.7.0/lib/prmd/templates/schemata.md.erb:26:in `result'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/prmd-0.7.0/lib/prmd/templates/schema.erb:7:in `block in result'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/prmd-0.7.0/lib/prmd/templates/schema.erb:4:in `each'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/prmd-0.7.0/lib/prmd/templates/schema.erb:4:in `map'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/prmd-0.7.0/lib/prmd/templates/schema.erb:4:in `result'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/prmd-0.7.0/lib/prmd/core/renderer.rb:49:in `render'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/prmd-0.7.0/lib/prmd/commands/render.rb:34:in `render'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/prmd-0.7.0/lib/prmd/cli/doc.rb:65:in `execute'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/prmd-0.7.0/lib/prmd/cli/base.rb:141:in `run'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/prmd-0.7.0/lib/prmd/cli.rb:93:in `run'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/gems/prmd-0.7.0/bin/prmd:6:in `<top (required)>'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/bin/prmd:23:in `load'
	from /Users/anthonator/.rbenv/versions/2.2.0/gemsets/captivated-customer-api/bin/prmd:23:in `<main>'
```

I'm obviously doing something wrong but for the life of me I can't figure it out. ```verify``` doesn't give me anything useful.

**Comment by geemus** [comment]
Yeah, that message is NOT helpful. In order to generate what the example response should look like, it expects that there be a property key at the top level which lists the attributes that should appear in the serialization. It looks like not having that tries to generate json from nil and fails. Does that make sense/help? Thanks!

**Comment by anthonator** [comment]
Yussssssssss!

This works:

```json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "id": "schemata/oauth2",
  "title": "Captivated Customer - OAuth2",
  "description": "Managing app accesss using OAuth2",
  "type": ["object"],
  "definitions": {
    "access_token": {
      "description": "Credentials used to access protected resources",
      "example": "asdf",
      "type": ["string"]
    }
  },
  "links": [
    {
      "title": "Request a User Access Token",
      "description": "Obtain a new access token for a specific user",
      "href": "/oauth/token",
      "method": "POST",
      "rel": "create"
    }
  ],
  "properties": {
    
  }
}
```

Adding the empty ```properties``` fixed it.

**Comment by geemus** [comment]
Sure thing, if there is a place where we could better document or make that clearer, let me know. If nothing else, maybe we should file an issue such that this situation would fail verify or something?

**Comment by anthonator** [comment]
Well, ```verify``` didn't properly validate the schema against my JSON. So I do think it's a failing with ```verify```.  So anything we can do to let people know what's wrong with their JSON would be great.

**Comment by geemus** [comment]
So, just getting a chance to dig back in to this. It verifies based on the value for $schema. What you have IS valid for hyper-schema, but interagent is a little more picky (in order to facilitate examples). I think if you change to using $schema of `http://interagent.github.io/interagent-hyper-schema`, it should be more strict and error on things like this (or other things that might prevent prmd from operating). Hope that helps, thanks!
