### ISSUE TITLE
prmd doc fails despite verify

### ISSUE THREAD

**Issue by johnbeynon** [interagent/prmd#201]
I'm getting an error

```
prmd combine --meta schema/meta.json schema/schemata/ | prmd verify | prmd doc > schema.md
/Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/prmd-0.7.0/lib/prmd/templates/schemata/helper.erb:100:in `build_attribute': undefined method `include?' for nil:NilClass (NoMethodError)
	from /Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/prmd-0.7.0/lib/prmd/templates/schemata/helper.erb:54:in `block in extract_attributes'
	from /Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/prmd-0.7.0/lib/prmd/templates/schemata/helper.erb:5:in `each'
	from /Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/prmd-0.7.0/lib/prmd/templates/schemata/helper.erb:5:in `extract_attributes'
	from /Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/prmd-0.7.0/lib/prmd/templates/schemata.md.erb:22:in `result'
	from /Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
	from /Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
	from /Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/prmd-0.7.0/lib/prmd/templates/schema.erb:7:in `block in result'
	from /Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/prmd-0.7.0/lib/prmd/templates/schema.erb:4:in `each'
	from /Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/prmd-0.7.0/lib/prmd/templates/schema.erb:4:in `map'
	from /Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/prmd-0.7.0/lib/prmd/templates/schema.erb:4:in `result'
	from /Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
	from /Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
	from /Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/prmd-0.7.0/lib/prmd/core/renderer.rb:49:in `render'
	from /Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/prmd-0.7.0/lib/prmd/commands/render.rb:34:in `render'
	from /Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/prmd-0.7.0/lib/prmd/cli/doc.rb:65:in `execute'
	from /Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/prmd-0.7.0/lib/prmd/cli/base.rb:141:in `run'
	from /Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/prmd-0.7.0/lib/prmd/cli.rb:93:in `run'
	from /Users/jbeynon/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/prmd-0.7.0/bin/prmd:6:in `<top (required)>'
	from /Users/jbeynon/.rbenv/versions/2.2.1/bin/prmd:23:in `load'
	from /Users/jbeynon/.rbenv/versions/2.2.1/bin/prmd:23:in `<main>'
```

When I try to generate docs.

speaking with @geemus - it's about type being required and needing to be an array - either way, it shouldn't blow up quite so spectacularly.

**Comment by geemus** [comment]
Yeah, we should probably ensure that type exists and is an array (or deal with it more gracefully when it isn't). I would have to dig in more to know for sure which is more sensible.

**Comment by JulienPalard** [comment]
Just got beaten by this.

**Comment by JulienPalard** [comment]
Telling us where the wrongly formed object is may be a nice help, my schema is not too big (only 833 lines :p) so I should find it, but I prefer when the when the computer do the work, not me.

**Comment by JulienPalard** [comment]
I put this in the same ticket as it's a "prmd doc fails despite verify", but it may be completly different:

I'm getting a:

```
Failed to dereference ``
Failed to dereference `#/definitions/social`
/var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/schema.rb:90:in `dereference': undefined method `gsub' for nil:NilClass (NoMethodError)
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/schema.rb:95:in `dereference'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/schema.rb:156:in `schemata_example'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/templates/schemata/link.md.erb:77:in `result'
        from /var/lib/gems/1.9.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
        from /var/lib/gems/1.9.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/template.rb:64:in `render'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/templates/schemata.md.erb:31:in `block in result'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/templates/schemata.md.erb:29:in `each'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/templates/schemata.md.erb:29:in `result'
        from /var/lib/gems/1.9.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
        from /var/lib/gems/1.9.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/templates/schema.erb:7:in `block in result'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/templates/schema.erb:4:in `each'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/templates/schema.erb:4:in `map'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/templates/schema.erb:4:in `result'
        from /var/lib/gems/1.9.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
        from /var/lib/gems/1.9.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/core/renderer.rb:49:in `render'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/commands/render.rb:34:in `render'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/cli/doc.rb:65:in `execute'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/cli/base.rb:141:in `run'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/cli.rb:93:in `run'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/bin/prmd:6:in `<top (required)>'
        from /usr/local/bin/prmd:23:in `load'
        from /usr/local/bin/prmd:23:in `<main>'
```

Yet the verify pass, I'm getting this running the `doc`.

Also I have no definitions/social in my json, I should probably not use caps in my definitions ?

**Comment by geemus** [comment]
Could you share the schema that you are using which results in the error? I think that will make it much easier for me to work back to the core issue. Thanks!

**Comment by kerlyn-bsd3** [comment]
Also getting wedged by the same symptom as @johnbeynon.  Do you need the schema?

**Comment by geemus** [comment]
@kerlyn-bsd3 sure, yeah, always helpful to have repro cases. Thanks!

**Comment by kerlyn-bsd3** [comment]
Is there a project email that I can send the failing schema to?  I don't want to just paste it here.  Thx.

**Comment by geemus** [comment]
@kerlyn-bsd3 the email on my profile would be fine if you'd like to use that. Thanks!

**Comment by kerlyn-bsd3** [comment]
In my case, it turned out I was missing "type" in one of my definitions. Re-reading
https://github.com/interagent/prmd/blob/master/docs/schemata.md helped!

**Comment by geemus** [comment]
Ah ha, thanks for sharing! Definitely let us know if you have any suggestions for what we could modify to make things clearer or easier. Thanks!

**Comment by yongwoondwango** [comment]
I also got errors as blow. How can I fix it ?

ykim:yongwoon_kim$ prmd doc ./schema.json > schema.md
.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/prmd-0.11.4/lib/prmd/templates/schemata/link_curl_example.md.erb:14:in `result': undefined method `upcase' for nil:NilClass (NoMethodError)
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/prmd-0.11.4/lib/prmd/template.rb:64:in `render'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/prmd-0.11.4/lib/prmd/templates/schemata/link.md.erb:37:in `result'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/prmd-0.11.4/lib/prmd/template.rb:64:in `render'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/prmd-0.11.4/lib/prmd/templates/schemata.md.erb:35:in `block in result'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/prmd-0.11.4/lib/prmd/templates/schemata.md.erb:33:in `each'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/prmd-0.11.4/lib/prmd/templates/schemata.md.erb:33:in `result'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/prmd-0.11.4/lib/prmd/templates/schema.erb:7:in `block in result'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/prmd-0.11.4/lib/prmd/templates/schema.erb:4:in `each'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/prmd-0.11.4/lib/prmd/templates/schema.erb:4:in `map'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/prmd-0.11.4/lib/prmd/templates/schema.erb:4:in `result'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/prmd-0.11.4/lib/prmd/core/renderer.rb:49:in `render'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/prmd-0.11.4/lib/prmd/commands/render.rb:34:in `render'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/prmd-0.11.4/lib/prmd/cli/doc.rb:65:in `execute'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/prmd-0.11.4/lib/prmd/cli/base.rb:141:in `run'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/prmd-0.11.4/lib/prmd/cli.rb:95:in `run'
	from .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/prmd-0.11.4/bin/prmd:6:in `<top (required)>'
	from .rbenv/versions/2.3.0/bin/prmd:23:in `load'
	from .rbenv/versions/2.3.0/bin/prmd:23:in `<main>'

**Comment by geemus** [comment]
@yongwoondwango that error would come from a link that didn't have a method defined it looks like, but the schema you have here does. Is this the only schema involved or are there others?

**Comment by yongwoondwango** [comment]
@geemus 
only schema involved.
I solve it as followed. the problem is the path of $ref.
```
  "properties": {
    "product_id": {
      "$ref": "/schemata/product#/definitions/product_id"
    }
  },
```

**Comment by geemus** [comment]
@yongwoondwango ah, got it, thanks for the update
