### ISSUE TITLE
prmd verify don't whine about missing "properties"

### ISSUE THREAD

**Issue by JulienPalard** [interagent/prmd#224]
I'm testing prmd, I tried to build my schema.json part by part to understand, so I created a version without "properties" and got:

```
/var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/templates/schema.erb:4:in `result': undefined method `map' for nil:NilClass (NoMethodError)
        from /var/lib/gems/1.9.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
        from /var/lib/gems/1.9.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/core/renderer.rb:49:in `render'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/commands/render.rb:34:in `render'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/cli/doc.rb:65:in `execute'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/cli/base.rb:141:in `run'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/lib/prmd/cli.rb:93:in `run'
        from /var/lib/gems/1.9.1/gems/prmd-0.7.3/bin/prmd:6:in `<top (required)>'
        from /usr/local/bin/prmd:23:in `load'
        from /usr/local/bin/prmd:23:in `<main>'
```

yet `prmd verify` passes, I think it should whine about it ? Or I misunderstood the `verify` tool.

**Comment by geemus** [comment]
Yeah, either verify should wine or the doc stuff should play nice when it is missing. I'd certainly welcome a patch, otherwise I'll try to get to it soon.

**Comment by JulienPalard** [comment]
I'll won't be able to produce a patch, almost never opened a ruby file my entire life, almost sorry about this. But this ticket have no urgency for me, I was just trying prmd for the fun and reporting to permit it enhancements.

**Comment by geemus** [comment]
Understood, could you share the schema you ran into this with? That will make it a bit easier for me to pin down the specific error and ensure things have been fixed. Thanks!
