### ISSUE TITLE
invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by reesew** [interagent/prmd#237]
I followed the commands in the typical workflow, and get the following error/trace
```
/usr/local/bundle/gems/erubis-2.7.0/lib/erubis/converter.rb:132:in `scan': invalid byte sequence in US-ASCII (ArgumentError)
        from /usr/local/bundle/gems/erubis-2.7.0/lib/erubis/converter.rb:132:in `convert_input'
        from /usr/local/bundle/gems/erubis-2.7.0/lib/erubis/converter.rb:36:in `convert'
        from /usr/local/bundle/gems/erubis-2.7.0/lib/erubis/engine.rb:30:in `initialize'
        from /usr/local/bundle/gems/prmd-0.7.4/lib/prmd/template.rb:45:in `new'
        from /usr/local/bundle/gems/prmd-0.7.4/lib/prmd/template.rb:45:in `load'
        from /usr/local/bundle/gems/prmd-0.7.4/lib/prmd/template.rb:54:in `load_template'
        from /usr/local/bundle/gems/prmd-0.7.4/lib/prmd/template.rb:64:in `render'
        from /usr/local/bundle/gems/prmd-0.7.4/lib/prmd/templates/schemata.md.erb:2:in `result'
        from /usr/local/bundle/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
        from /usr/local/bundle/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
        from /usr/local/bundle/gems/prmd-0.7.4/lib/prmd/templates/schema.erb:7:in `block in result'
        from /usr/local/bundle/gems/prmd-0.7.4/lib/prmd/templates/schema.erb:4:in `each'
        from /usr/local/bundle/gems/prmd-0.7.4/lib/prmd/templates/schema.erb:4:in `map'
        from /usr/local/bundle/gems/prmd-0.7.4/lib/prmd/templates/schema.erb:4:in `result'
        from /usr/local/bundle/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
        from /usr/local/bundle/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
        from /usr/local/bundle/gems/prmd-0.7.4/lib/prmd/core/renderer.rb:49:in `render'
        from /usr/local/bundle/gems/prmd-0.7.4/lib/prmd/commands/render.rb:34:in `render'
        from /usr/local/bundle/gems/prmd-0.7.4/lib/prmd/cli/doc.rb:65:in `execute'
        from /usr/local/bundle/gems/prmd-0.7.4/lib/prmd/cli/base.rb:141:in `run'
        from /usr/local/bundle/gems/prmd-0.7.4/lib/prmd/cli.rb:93:in `run'
        from /usr/local/bundle/gems/prmd-0.7.4/bin/prmd:6:in `<top (required)>'
        from /usr/local/bundle/bin/prmd:23:in `load'
        from /usr/local/bundle/bin/prmd:23:in `<main>'
```

**Comment by reesew** [comment]
nevermind, this was a docker problem, solved by [this article](http://jaredmarkell.com/docker-and-locales/)

**Comment by geemus** [comment]
Thanks for the update, I've also run into that issue and it was frustrating
to figure out. Glad you are back in working order.

**Comment by parikhparth23** [comment]
same error

**Comment by geemus** [comment]
@parikhparth23 are you in a docker environment? Could you share some additional details to help us narrow it down? Thanks!

**Comment by parikhparth23** [comment]
@geemus i followed the steps by reesew...any added the environment variable in Jenkins and it is working fine now!
Thank you for your reply!

**Comment by geemus** [comment]
Thanks for the update, glad to hear it!

**Comment by 110y** [comment]
I also faced this error, and fixed by below:

```
RUN locale-gen en_US.UTF-8
RUN localedef -f UTF-8 -i en_US en_US.UTF-8

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
```
