### ISSUE TITLE
Prmd::Link::OpenStuct (NameError)

### ISSUE THREAD

**Issue by stepan-perlov** [interagent/prmd#244]
Good day.

```dash
$ prmd
/usr/lib/ruby/gems/1.9.1/gems/prmd-0.8.0/bin/prmd
/usr/lib/ruby/gems/1.9.1/gems/prmd-0.8.0/lib/prmd/link.rb:45:in `<class:Link>': uninitialized constant Prmd::Link::OpenStruct (NameError)
	from /usr/lib/ruby/gems/1.9.1/gems/prmd-0.8.0/lib/prmd/link.rb:2:in `<module:Prmd>'
	from /usr/lib/ruby/gems/1.9.1/gems/prmd-0.8.0/lib/prmd/link.rb:1:in `<top (required)>'
	from /usr/lib/ruby/gems/1.9.1/gems/prmd-0.8.0/lib/prmd.rb:5:in `require_relative'
	from /usr/lib/ruby/gems/1.9.1/gems/prmd-0.8.0/lib/prmd.rb:5:in `<top (required)>'
	from /usr/lib/ruby/gems/1.9.1/gems/prmd-0.8.0/bin/prmd:3:in `require_relative'
	from /usr/lib/ruby/gems/1.9.1/gems/prmd-0.8.0/bin/prmd:3:in `<top (required)>'
	from /usr/local/bin/prmd:25:in `load'
	from /usr/local/bin/prmd:25:in `<main>'
```

When comments in prmd/lib/prmd/links.rb

```ruby
   """
   class Schema < OpenStruct
      def has_properties?
        !self.properties.empty?
      end

      def property_is_required?(property_name)
        return false unless required
        return required.include?(property_name)
      end
    end
    """
```
then prmd command work

```dash
$ prmd --version
/usr/lib/ruby/gems/1.9.1/gems/prmd-0.8.0/bin/prmd
prmd 0.8.0
```

OS: Ubuntu 14.04.3 LTS

**Comment by geemus** [comment]
I suspect it might be a missing `require "openstruct"`. Could you try with that addition and see if it helps in your case? You might also consider updating to a newer ruby as 1.9.1 is fairly dated at this point.

**Comment by stepan-perlov** [comment]
yes. works with ruby 2.1.3

**Comment by geemus** [comment]
Thanks for the update, I think maybe at some point Ruby started requiring openstruct by default.
