### ISSUE TITLE
Cannot generate Schema

### ISSUE THREAD

**Issue by shideneyu** [interagent/prmd#258]
Hi, Using `prmd` 0.8.0 , I try to convert this schema that I took from http://json-schema.org/example2.html

	{
		"id": "http://some.site.somewhere/entry-schema#",
		"$schema": "http://json-schema.org/draft-04/schema#",
		"description": "schema for an fstab entry",
		"type": "object",
		"required": [ "storage" ],
		"properties": {
		    "storage": {
		        "type": "object",
		        "oneOf": [
		            { "$ref": "#/definitions/diskDevice" },
		            { "$ref": "#/definitions/diskUUID" },
		            { "$ref": "#/definitions/nfs" },
		            { "$ref": "#/definitions/tmpfs" }
		        ]
		    }
		},
		"definitions": {
		    "diskDevice": {},
		    "diskUUID": {},
		    "nfs": {},
		    "tmpfs": {}
		}
	}

So I run this: `prmd doc schema.json > schema.md``. And I get this:

    /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/prmd-0.8.0/lib/prmd/templates/schemata.md.erb:9:in `result': undefined method `split' for nil:NilClass (NoMethodError)
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/prmd-0.8.0/lib/prmd/templates/schema.erb:7:in `block in result'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/prmd-0.8.0/lib/prmd/templates/schema.erb:4:in `each'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/prmd-0.8.0/lib/prmd/templates/schema.erb:4:in `map'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/prmd-0.8.0/lib/prmd/templates/schema.erb:4:in `result'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/prmd-0.8.0/lib/prmd/core/renderer.rb:49:in `render'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/prmd-0.8.0/lib/prmd/commands/render.rb:34:in `render'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/prmd-0.8.0/lib/prmd/cli/doc.rb:65:in `execute'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/prmd-0.8.0/lib/prmd/cli/base.rb:141:in `run'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/prmd-0.8.0/lib/prmd/cli.rb:93:in `run'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/prmd-0.8.0/bin/prmd:6:in `<top (required)>'
      from /home/shideneyu/.rbenv/versions/2.1.2/bin/prmd:23:in `load'
      from /home/shideneyu/.rbenv/versions/2.1.2/bin/prmd:23:in `<main>'

This looks like Issue #160, but is quite different. I couldn't find what's going wrong.

Thanks for your hard work.

**Comment by gottfrois** [comment]
If you read the generated file it says `Error in resource: storage`. Adding `"title": "foo"` here works:

```
"storage": {
  "title": "foo",
  "type": "object",
  "oneOf": [
    { "$ref": "#/definitions/diskDevice" },
    { "$ref": "#/definitions/diskUUID" },
    { "$ref": "#/definitions/nfs" },
    { "$ref": "#/definitions/tmpfs" }
  ]
}
```

**Comment by shideneyu** [comment]
But the schema documentaiton markdown is then corrupted:

    ➜  ~  cat schema.md 
    ## <a name="resource-storage"></a>foo

**Comment by MasseR** [comment]
@shideneyu as a workaround, you can do something like this:

~~~~
prmd doc schema.json | perl -pe 's|^## <a name="(.*?)"></a>(.*$)|## \2|'
~~~~

**Comment by shideneyu** [comment]
Thx for your answer, @MasseR . It seems that it doesn't do much good though.

		➜  prmd  ls
		schema.json
		➜  prmd  prmd doc schema.json
		## <a name="resource-storage"></a>foo




		➜  prmd  ls
		schema.json
		➜  prmd  prmd doc schema.json | perl -pe 's|^## <a name="(.*?)"></a>(.*$)|## \2|'
		## foo




		➜  prmd  ls
		schema.json

**Comment by geemus** [comment]
I think there are a couple things at play here.

First off, we have a few additional conventions on top of json-schema that we use, which we have found to be helpful. In particular, we put each resource in it's own schema and then use `prmd combine schemata/` to create a full schema, which we then would run through doc/etc. In this case, the schema you use in the example looks more like what I would expect to fit into one of these sub-schema, rather than a parent schema. So running it through combine first (ideally with a valid meta file, which can be created with `prmd init`) should get you closer to what you want.

Similarly, we also have layer on the idea of title to help provide a nice label for documentation. It is expected that this would appear both in the sub-resource (like storage) and the top level. That being said, I could see us loosening this expectation and conditionally including the tile depending on if it is present or not (or trying to infer the title from filename or something), but just requiring it is easier and can hopefully result in a nicer final output in most cases.

Does that help/make sense? I'm certainly happy to help/discuss further. Thanks!

**Comment by taylorp0994** [comment]
@geemus I was running into issue #265 before stumbling across this issue as well. Has there been any progress on this since 2015? I'm trying to implement a console app that uses the `Prmd::Render` module, but I keep getting the fatal `Error in resource:` message on what I know to be valid JSON Schema. Is this a known bug? Is a reasonable workaround available? I don't understand what you mean by "additional conventions on top of json-schema". Do these break the core JSON Schema syntax?

**Comment by geemus** [comment]
@taylorp0994 hey, I ended up changing teams and other things which moved me away from using this on a regular basis some time ago. So I personally don't have much to report in terms of changes I'm afraid. I'm happy to try to clarify and support as best I can though.

I'm not sure about that error off hand, it doesn't relate to known bugs that I'm aware of anyway. It's hard for me to say without seeing the schema in question what might be the problem and/or workaround.

We found that json-schema lacked a few fields that we thought would be useful to flesh out documentation, so prmd was setup to use some extra fields if (and I think only if) they exist. They are intended to optional and additive on top of JSON Schema though, not breaking changes. Does that make more sense?
